services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf/:ro
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /var/www/certbot:/var/www/certbot:ro
      - ./reload-cert.sh:/docker-entrypoint.d/reload-cert.sh:ro
  cert-renew:
    container_name: cert-renew
    build:
      context: .
      dockerfile: ./certbot/renew/dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /var/www/certbot:/var/www/certbot:rw
