services:
  certbot-init:
    image: certbot/certbot:latest
    container_name: certbot-init
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
    ports:
      - "80:80"
    command: certonly --standalone --non-interactive --email ericrovell@gmail.com --agree-tos --preferred-challenges http -d "escapist-marginalia.tech,en.escapist-marginalia.tech,ru.escapist-marginalia.tech"