<script lang="ts">
	import { InputColor, InputRange, InputSwitch } from "ui";

	import InputRestrictions from "./chaos-game.restrictions.svelte";
	import { SketchControls } from "@components";
	import { options, optionsImmutable } from "./chaos-game.options";

	export let t: Record<string, string>;
	export let state: typeof options = {
		...options
	};
</script>

<SketchControls bind:state on:reset {optionsImmutable} {options}>
	<fieldset>
		<legend>
			Polygon
		</legend>
		<InputRange
			output
			bind:value="{state["polygon-sides"]}"
			name="polygon-sides"
			min="{3}"
			max="{12}"
		>
			{t["polygon-sides"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-scale"]}"
			name="polygon-scale"
			min="{0.1}"
			max="{2}"
			step="{0.01}"
		>
			{t["polygon-scale"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-origin-theta"]}"
			name="polygon-origin-theta"
			min="{0}"
			max="{360}"
		>
			{t["polygon-origin-theta"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-line-width"]}"
			name="polygon-line-width"
			min="{0.5}"
			max="{5}"
			step="{0.5}"
			disabled="{!state["polygon-visible"]}"
		>
			{t["polygon-line-width"]}
		</InputRange>
		<InputSwitch
			bind:checked="{state["polygon-visible"]}"
			name="polygon-visible"
		>
			{t["polygon-visible"]}
		</InputSwitch>
		<InputColor
			bind:value="{state["polygon-color"]}"
			name="polygon-color"
			disabled="{!state["polygon-visible"]}"
		>
			{t["polygon-color"]}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Marks
		</legend>
		<InputRange
			output
			bind:value="{state["points-limit"]}"
			name="points-limit"
			min="{1}"
			max="{500000}"
		>
			{t["points-limit"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["point-scale"]}"
			name="point-scale"
			min="{0.1}"
			max="{5}"
			step="{0.1}"
		>
			{t["point-scale"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["speed"]}"
			name="speed"
			min="{1}"
			max="{150}"
		>
			{t["speed"]}
		</InputRange>
		<InputSwitch
			bind:checked="{state["points-color-wheel"]}"
			name="points-color-wheel"
		>
			{t["points-color-wheel"]}
		</InputSwitch>
		<InputColor
			bind:value="{state["points-color"]}"
			name="points-color"
			disabled="{state["points-color-wheel"]}"
		>
			{t["polygon-color"]}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Step
		</legend>
		<InputSwitch
			bind:checked="{state["step-factor"]}"
			name="step-factor"
		>
			{t["step-factor"]}
		</InputSwitch>
		<InputRange
			output
			bind:value="{state["step-coef"]}"
			disabled="{!state["step-factor"]}"
			name="step-coef"
			min="{0.01}"
			max="{1.5}"
			step="{0.01}"
		>
			{t["step-coef"]}
		</InputRange>
		<InputRange
			output
			bind:value="{state["step-distance"]}"
			disabled="{state["step-factor"]}"
			name="step-distance"
			min="{0.1}"
			max="{1000}"
			step="{0.1}"
		>
			{t["step-distance"]}
		</InputRange>
	</fieldset>
	<InputRestrictions
		bind:value="{state["restrictions"]}"
		sides="{state["polygon-sides"]}"
		{t}
	>
		{t["restrictions"]}
	</InputRestrictions>
</SketchControls>
