<script lang="ts">
	import { getContext } from "svelte";
	import { InputColor, InputRange, InputSwitch } from "ui";

	import InputRestrictions from "./chaos-game.restrictions.svelte";
	import { SketchControls } from "$lib/components";
	import { DEFAULT_OPTIONS, IMMUTABLE_OPTIONS } from "./chaos-game.options";
	import type { Translation } from "../translations/types";

	export let state: typeof DEFAULT_OPTIONS = {
		...DEFAULT_OPTIONS
	};

	const t = getContext<Translation>("t");
</script>

<SketchControls
	bind:state
	on:reset
	optionsImmutable="{IMMUTABLE_OPTIONS}"
	options="{DEFAULT_OPTIONS}"
>
	<fieldset>
		<legend>
			Polygon
		</legend>
		<InputRange
			output
			bind:value="{state["polygon-sides"]}"
			name="polygon-sides"
			min="{3}"
			max="{12}"
		>
			{t.POLYGON_SIDES}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-scale"]}"
			name="polygon-scale"
			min="{0.1}"
			max="{2}"
			step="{0.01}"
		>
			{t.POLYGON_SCALE}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-origin-theta"]}"
			name="polygon-origin-theta"
			min="{0}"
			max="{360}"
		>
			{t.POLYGON_ORIGIN_THETA}
		</InputRange>
		<InputRange
			output
			bind:value="{state["polygon-line-width"]}"
			name="polygon-line-width"
			min="{0.5}"
			max="{5}"
			step="{0.5}"
			disabled="{!state["polygon-visible"]}"
		>
			{t.POLYGON_LINE_WIDTH}
		</InputRange>
		<InputSwitch
			bind:checked="{state["polygon-visible"]}"
			name="polygon-visible"
		>
			{t.POLYGON_VISIBLE}
		</InputSwitch>
		<InputColor
			bind:value="{state["polygon-color"]}"
			name="polygon-color"
			disabled="{!state["polygon-visible"]}"
		>
			{t.POLYGON_COLOR}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Marks
		</legend>
		<InputRange
			output
			bind:value="{state["points-limit"]}"
			name="points-limit"
			min="{1}"
			max="{500000}"
		>
			{t.POINTS_LIMIT}
		</InputRange>
		<InputRange
			output
			bind:value="{state["point-scale"]}"
			name="point-scale"
			min="{0.1}"
			max="{5}"
			step="{0.1}"
		>
			{t.POINT_SCALE}
		</InputRange>
		<InputRange
			output
			bind:value="{state["speed"]}"
			name="speed"
			min="{1}"
			max="{150}"
		>
			{t.SPEED}
		</InputRange>
		<InputSwitch
			bind:checked="{state["points-color-wheel"]}"
			name="points-color-wheel"
		>
			{t.POINTS_COLOR_WHEEL}
		</InputSwitch>
		<InputColor
			bind:value="{state["points-color"]}"
			name="points-color"
			disabled="{state["points-color-wheel"]}"
		>
			{t.POLYGON_COLOR}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Step
		</legend>
		<InputSwitch
			bind:checked="{state["step-factor"]}"
			name="step-factor"
		>
			{t.STEP_FACTOR}
		</InputSwitch>
		<InputRange
			output
			bind:value="{state["step-coef"]}"
			disabled="{!state["step-factor"]}"
			name="step-coef"
			min="{0.01}"
			max="{1.5}"
			step="{0.01}"
		>
			{t.STEP_COEF}
		</InputRange>
		<InputRange
			output
			bind:value="{state["step-distance"]}"
			disabled="{state["step-factor"]}"
			name="step-distance"
			min="{0.1}"
			max="{1000}"
			step="{0.1}"
		>
			{t.STEP_DISTANCE}
		</InputRange>
	</fieldset>
	<InputRestrictions
		bind:value="{state["restrictions"]}"
		sides="{state["polygon-sides"]}"
	>
		{t.RESTRICTIONS}
	</InputRestrictions>
</SketchControls>
