name: build

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.4.1
          run_install: false
      - name: install-node-js
        uses: actions/setup-node@master
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: install-dependencies
        run: pnpm i -r
      - name: eslint
        run: pnpm lint:code
      - name: stylelint
        run: pnpm lint:styles
      - name: typescript
        run: pnpm lint:types
      - name: unit-testing
        run: pnpm test:unit:ci
      - name: unit-testing-coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage
          if-no-files-found: error
      - name: build-en
        run: pnpm build
      - name: build-en-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-en
          path: ./src/packages/escapist-marginalia/dist
          if-no-files-found: error
      - name: build-ru
        run: LANG=ru pnpm build
      - name: build-ru-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-ru
          path: ./src/packages/escapist-marginalia/dist-ru
          if-no-files-found: error
